# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTable',
            fields=[
                ('title_hash', models.CharField(max_length=56, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('source', models.CharField(max_length=50)),
                ('content', models.CharField(blank=True, max_length=6000, null=True)),
                ('date', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'article_table',
                'managed': True,
            },
        ),
    ]
